apiVersion: v1
kind: Service
metadata:
  name: challenge2svc
spec:
  selector:
    app: minecraft
  ports:
    - protocol: "TCP"
      port: 25565
      targetPort: 25565
    - protocol: "TCP"
      port: 25575
      targetPort: 25575
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge2dep
  labels:
    app: minecraft
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: openhack/minecraft-server:2.0
          ports:
            - containerPort: 25565
            - containerPort: 25575
          env:
            - name: EULA
              value: "TRUE"
          volumeMounts:
            - mountPath: "/data/"
              name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azurefile
