apiVersion: v1
kind: Service
metadata:
  name: challenge2svc
spec:
  selector:
    app: minecraft
  ports:
  - protocol: "TCP"
    port: 25565
    targetPort: 25565
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge2dep
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image:  openhack/minecraft-server:1.0
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
