kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefilegeo
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_GRS
  storageAccount: georedundantopenhack01
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:azure-cloud-provider
rules:
- apiGroups: ['']
  resources: ['secrets']
  verbs:     ['get','create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:azure-cloud-provider
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:azure-cloud-provider
subjects:
- kind: ServiceAccount
  name: persistent-volume-binder
  namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefilegeo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefilegeo
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: challenge2svcmod
spec:
  selector:
    app: minecraftmod
  ports:
  - protocol: "TCP"
    name: mc-port
    port: 25565
    targetPort: 25565
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge2depmod
  labels:
    app: minecraftmod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraftmod
  template:
    metadata:
      labels:
        app: minecraftmod
    spec:
      containers:
      - name: minecraftmod
        image:  relent0r/minecraft-server:1.0-alpine
        ports:
        - containerPort: 25565
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - mountPath: "/data/"
          name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azurefilegeo
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: challenge2scalemod
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: challenge2depmod
  targetCPUUtilizationPercentage: 50