apiVersion: v1
kind: Service
metadata:
  name: challenge2svcmod
spec:
  selector:
    app: minecraftmod
  ports:
  - protocol: "TCP"
    name: mc-port
    port: 25565
    targetPort: 25565
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge2depmod
  labels:
    app: minecraftmod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraftmod
  template:
    metadata:
      labels:
        app: minecraftmod
    spec:
      containers:
      - name: minecraftmod
        image:  relent0r/minecraft-server:1.0-alpine
        ports:
        - containerPort: 25565
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - mountPath: "/data/"
          name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azurefile
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: challenge2scalemod
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: challenge2depmod
  targetCPUUtilizationPercentage: 50
  
  